yzu_course_info_API/Models/Member.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace yzu_course_info_API.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Member()
        {
            this.Comment = new HashSet<Comment>();
        }
    
        public string mId { get; set; }
        public string mPwd { get; set; }
        public string mNickname { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Comment> Comment { get; set; }
    }
}

yzu_course_info_API/ViewModels/LoginViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Security.Cryptography;
using System.Text;
using System.Web;
using System.Web.Security;
using yzu_course_info_API.Models;

namespace yzu_course_info_API.ViewModels
{
    public class LoginViewModel : IValidatableObject
    {

        private Entities db = new Entities();


        [DisplayFormat(ConvertEmptyStringToNull = false)]
        public string ReturnUrl { get; set; }

        /// <summary>
        /// 帳號
        /// </summary>
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "請輸入帳號")]
        [DisplayName("帳號")]
        public string mId { get; set; }

        /// <summary>
        /// 密碼
        /// </summary>
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "請輸入密碼")]
        [DisplayName("密碼")]
        public string mPwd { get; set; }

        /// <summary>
        /// 暱稱
        /// </summary>
        public string mNickname { get; set; } = "teset";

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            //到DB抓使用者資料
            Member member = db.Member.Find(mId);
            //將使用者輸入的字串加密
            SHA512 sha512 = new SHA512CryptoServiceProvider();
            string cryptedPwd = Convert.ToBase64String(sha512.ComputeHash(Encoding.Default.GetBytes(mPwd)));
            
            //假如抓不到系統使用者資料
            if (!(member != null && cryptedPwd == member.mPwd))
            {
                yield return new ValidationResult("帳號或密碼錯誤", new string[] { "Account" });
            }

            try { mNickname = member.mNickname; }
            catch { }
           
        }
        
    }
}

yzu_course_info_API/ViewModels/MemberViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Migrations;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Security;
using System.Security.Cryptography;
using yzu_course_info_API.Models;
using System.Text;


namespace yzu_course_info_API.ViewModels
{
    public class MemberViewModel : IValidatableObject
    {

        private Entities db = new Entities();

        /// <summary>
        /// 帳號
        /// </summary>
        public string mId { get; set; }

        /// <summary>
        /// 密碼
        /// </summary>
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "請輸入密碼")]
        [DisplayName("密碼")]
        public string mPwd { get; set; }

        /// <summary>
        /// 密碼確認
        /// </summary>
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "請輸入密碼")]
        [DisplayName("密碼確認")]
        [Compare("mPwd", ErrorMessage = "輸入的密碼與上列不同")]
        public string ConfirmPwd { get; set; }

        /// <summary>
        /// 暱稱
        /// </summary>        
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "請輸入暱稱")]
        [DisplayName("暱稱")]
        public string mNickname { get; set; }
        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            //到DB抓使用者資料 看有沒有重複的使用者帳號
            Member member = db.Member.Find(mId);
            if (member == null)
                yield return new ValidationResult("抓不到你是誰呢....", new string[] { "Account" });

            //將使用者輸入的字串加密
            SHA512 sha512 = new SHA512CryptoServiceProvider();
            string cryptedPwd = Convert.ToBase64String(sha512.ComputeHash(Encoding.Default.GetBytes(mPwd)));

            /*db.Entry(new Member
            {
                mId = mId,
                mPwd = cryptedPwd,
                mNickname = mNickname
            }).State = EntityState.Modified;
            db.SaveChanges();*/

            db.Member.AddOrUpdate(new Member
            {
                mId = mId,
                mPwd = cryptedPwd,
                mNickname = mNickname
            });
            db.SaveChanges();
        }

        // 最安全請用 MembershipProvider

        // https://stackoverflow.com/questions/18493683/mvc-insert-post-data-into-database
    }
}

yzu_course_info_API/ViewModels/RegisterViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Web.Security;
using yzu_course_info_API.Models;
using System.Text;
using System.Security.Cryptography;

namespace yzu_course_info_API.ViewModels
{
    public class RegisterViewModel : IValidatableObject
    {

        private Entities db = new Entities();

        /// <summary>
        /// 帳號
        /// </summary>
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "請輸入帳號")]
        [DisplayName("帳號")]
        public string mId { get; set; }

        /// <summary>
        /// 密碼
        /// </summary>
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "請輸入密碼")]
        [DisplayName("密碼")]
        public string mPwd { get; set; }

        /// <summary>
        /// 密碼確認
        /// </summary>
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "請輸入密碼")]
        [DisplayName("密碼確認")]
        [Compare("mPwd", ErrorMessage = "輸入的密碼與上列不同")]
        public string ConfirmPwd { get; set; }

        /// <summary>
        /// 暱稱
        /// </summary>        
        [DisplayFormat(ConvertEmptyStringToNull = false)]
        [Required(ErrorMessage = "請輸入暱稱")]
        [DisplayName("暱稱")]
        public string mNickname { get; set; }

        public IEnumerable<ValidationResult> Validate(ValidationContext validationContext)
        {
            //到DB抓使用者資料 看有沒有重複的使用者帳號
            Member member = db.Member.Find(mId);
            if (member != null)
                yield return new ValidationResult("帳號已存在", new string[] { "Account" });

            //將使用者輸入的字串加密
            SHA512 sha512 = new SHA512CryptoServiceProvider();
            string cryptedPwd = Convert.ToBase64String(sha512.ComputeHash(Encoding.Default.GetBytes(mPwd)));

            try
            {
                db.Member.Add(new Member
                {
                    mId = mId,
                    mPwd = cryptedPwd,
                    mNickname = mNickname
                });
                db.SaveChanges();
            }
            catch { new ValidationResult("發生錯誤", new string[] { "Account" }); }


        }

        // 最安全請用 MembershipProvider

        // https://stackoverflow.com/questions/18493683/mvc-insert-post-data-into-database
    }
}

yzu_course_info_API/Controllers/ForumController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;

namespace yzu_course_info_API.Controllers
{
    [Authorize]
    public class ForumController : Controller
    {
        // GET: Forum
        [AllowAnonymous]
        public ActionResult Index()
        {
            ViewBag.Title = "論壇";
            return View();
        }
        
        // GET:/Forum/CourseDetails?cId=
        public ActionResult CourseDetails(string cId)
        {
            FormsIdentity id = (FormsIdentity)User.Identity;
            FormsAuthenticationTicket ticket = id.Ticket;
            ViewBag.nickname = ticket.UserData;
            ViewBag.mId = ticket.Name;
            ViewBag.course = cId;
            ViewBag.Title = "課程討論區";
            return View();
        }
    }
}

yzu_course_info_API/Controllers/MemberController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using yzu_course_info_API.Models;
using yzu_course_info_API.ViewModels;

namespace yzu_course_info_API.Controllers
{

    /// <summary>
    /// 後台首頁、登入頁...
    /// </summary>
    [Authorize]
    public class MemberController : Controller
    {
        private Entities db = new Entities();

        /// <summary>
        /// 呈現後台使用者登入頁
        /// </summary>
        /// <param name="ReturnUrl">使用者原本Request的Url</param>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult Login(string ReturnUrl)
        {
            if (Request.IsAuthenticated)
                return RedirectToAction("Index");
            ViewBag.Title = "登入";
            //ReturnUrl字串是使用者在未登入情況下要求的的Url
            LoginViewModel lvm = new LoginViewModel() { ReturnUrl = ReturnUrl };
            return View(lvm);
        }

        /// <summary>
        /// 後台使用者進行登入
        /// </summary>
        /// <param name="vm"></param>
        /// <param name="u">使用者原本Request的Url</param>
        /// <returns></returns>
        [AllowAnonymous]
        [HttpPost]
        public ActionResult Login(LoginViewModel lvm)
        {

            //沒通過Model驗證(必填欄位沒填，DB無此帳密)
            if (!ModelState.IsValid)
            {
                return View(lvm);
            }


            //都成功時 進行表單登入
            FormsAuthenticationTicket ticket = new FormsAuthenticationTicket(1,
                lvm.mId,//你想要存放在 User.Identy.Name 的值，通常是使用者帳號
                DateTime.Now,
                DateTime.Now.AddMinutes(10),
                false,//將管理者登入的 Cookie 設定成 Session Cookie
                lvm.mNickname,//userdata看你想存放啥
                FormsAuthentication.FormsCookiePath);

            string encTicket = FormsAuthentication.Encrypt(ticket);
            var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, encTicket);
            cookie.Expires = DateTime.Now.AddMinutes(10);
            Response.Cookies.Add(cookie);

            //導向預設Url

            //(1) 使用者原先Request的Url
            //FormsAuthentication.RedirectFromLoginPage(lvm.mId, false);
            try { Response.Redirect(this.Request.QueryString["ReturnUrl"]); }
            catch { }
            //(2) Web.config裡的defaultUrl定義 (若剛剛已導向，此行不會執行到)
            return Redirect(FormsAuthentication.GetRedirectUrl(lvm.mId, false));
        }

        /// <summary>
        /// 後台使用者登出動作
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult Logout()
        {
            //清除Session中的資料
            Session.Abandon();
            //登出表單驗證
            FormsAuthentication.SignOut();
            //導至登入頁
            return RedirectToAction("Login", "Member");
        }


        /// <summary>
        /// 註冊頁面
        /// </summary>
        /// <returns></returns>
        [AllowAnonymous]
        public ActionResult Register()
        {
            ViewBag.Title = "註冊";
            return View();
        }


        /// <summary>
        /// 註冊實做
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        [AllowAnonymous]
        public ActionResult Register(RegisterViewModel rvm)
        {
            //沒通過Model驗證(必填欄位沒填，DB無此帳密)
            if (!ModelState.IsValid)
            {
                return View(rvm);
            }
            return RedirectToAction("Login");
        }

        /// <summary>
        /// 後台首頁 
        /// </summary>
        /// <returns></returns>
        public ActionResult Index()
        {
            ViewBag.Title = "會員中心";
            try
            {
                FormsIdentity id = (FormsIdentity)User.Identity;
                FormsAuthenticationTicket ticket = id.Ticket;
                ViewBag.usrNickname = ticket.UserData;
            }
            catch { }
            return View();
        }

        /// <summary>
        /// 後台實做
        /// </summary>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Index(MemberViewModel mvm)
        {

            if (!ModelState.IsValid)
            {
                return View(mvm);
            }

            return RedirectToAction("Logout");
        }
    }
}

yzu_course_info_API/Controllers/MembersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;
using System.Web.Http.ModelBinding;
using System.Web.Http.OData;
using System.Web.Http.OData.Routing;
using yzu_course_info_API.Models;

namespace yzu_course_info_API.Controllers
{
    public class MembersController : ODataController
    {
        private Entities db = new Entities();

        // GET: api/Members
        [EnableQuery]
        public IQueryable<Member> GetMembers()
        {
            return db.Member;
        }

        // GET: api/Members(5)
        [EnableQuery]
        public SingleResult<Member> GetMember([FromODataUri] string key)
        {
            return SingleResult.Create(db.Member.Where(member => member.mId == key));
        }

        // PUT: api/Members(5)
        public IHttpActionResult Put([FromODataUri] string key, Delta<Member> patch)
        {
            Validate(patch.GetEntity());

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            Member member = db.Member.Find(key);
            if (member == null)
            {
                return NotFound();
            }

            patch.Put(member);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MemberExists(key))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return Updated(member);
        }

        // POST: api/Members
        public IHttpActionResult Post(Member member)
        {
            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            db.Member.Add(member);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateException)
            {
                if (MemberExists(member.mId))
                {
                    return Conflict();
                }
                else
                {
                    throw;
                }
            }

            return Created(member);
        }

        // PATCH: api/Members(5)
        [AcceptVerbs("PATCH", "MERGE")]
        public IHttpActionResult Patch([FromODataUri] string key, Delta<Member> patch)
        {
            Validate(patch.GetEntity());

            if (!ModelState.IsValid)
            {
                return BadRequest(ModelState);
            }

            Member member = db.Member.Find(key);
            if (member == null)
            {
                return NotFound();
            }

            patch.Patch(member);

            try
            {
                db.SaveChanges();
            }
            catch (DbUpdateConcurrencyException)
            {
                if (!MemberExists(key))
                {
                    return NotFound();
                }
                else
                {
                    throw;
                }
            }

            return Updated(member);
        }

        // DELETE: api/Members(5)
        public IHttpActionResult Delete([FromODataUri] string key)
        {
            Member member = db.Member.Find(key);
            if (member == null)
            {
                return NotFound();
            }

            db.Member.Remove(member);
            db.SaveChanges();

            return StatusCode(HttpStatusCode.NoContent);
        }

        // GET: api/Members(5)/Comment
        [EnableQuery]
        public IQueryable<Comment> GetComment([FromODataUri] string key)
        {
            return db.Member.Where(m => m.mId == key).SelectMany(m => m.Comment);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        private bool MemberExists(string key)
        {
            return db.Member.Count(e => e.mId == key) > 0;
        }
    }
}

yzu_course_info_API/Views/Member/Index.cshtml
@using yzu_course_info_API.ViewModels
@model MemberViewModel
<h2>會員中心</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>修改會員資料</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(m => m.mId, new { Value = User.Identity.Name })

        <div class="form-group">
            @Html.LabelFor(m => m.mPwd, "密碼", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.mPwd, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.mPwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ConfirmPwd, "確認密碼", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.ConfirmPwd, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ConfirmPwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.mNickname, "暱稱", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.mNickname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.mNickname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="儲存變更" class="btn btn-default" />
            </div>
        </div>
        <br />
        @Html.ValidationSummary(null, new { @class = "text-danger" })
    </div>
}

<div>
    @Html.ActionLink("回到論壇", "Index", "Forum", new { area = "" }, null)
    <div>我只是要<a href="@Url.Action("Logout","Member")">登出</a>而已</div>
</div>





<h2>你的暱稱：@ViewBag.usrNickname</h2>
<h2>你的帳號：@User.Identity.Name</h2>

yzu_course_info_API/Views/Member/Login.cshtml
@using yzu_course_info_API.ViewModels
@model LoginViewModel

<h2>登入</h2>
@*如果↓表單的ReturnUrl沒給的話，就沒辦法導向使用者原先要求的頁面*@
@using (Html.BeginForm("Login", "Member", new { ReturnUrl = Model.ReturnUrl }, FormMethod.Post, new { autocomplete = "off" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>登入論壇</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.mId, "帳號", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.mId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.mId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.mPwd, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.mPwd, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.mPwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="登入" class="btn btn-default" />
            </div>
        </div>
        <br />
        @Html.ValidationSummary(null, new { @class = "text-danger" })
    </div>
}
<div>
    沒有帳號嗎？@Html.ActionLink("註冊", "Register")
</div>

@*
    參考資料：
    http://demo.tc/post/534
    https://dotblogs.com.tw/shadow/archive/2014/03/01/144191.aspx
    http://www.debugease.com/aspdotnet/1993308.html
    https://dotblogs.com.tw/magic/2011/12/31/64050
*@

yzu_course_info_API/Views/Member/Register.cshtml
@using yzu_course_info_API.ViewModels
@model RegisterViewModel

<h2>註冊</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>註冊成為使用者</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(m => m.mId, "帳號", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.mId, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.mId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.mPwd, "密碼", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.mPwd, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.mPwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.ConfirmPwd, "確認密碼", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.PasswordFor(m => m.ConfirmPwd, new { @class = "form-control" })
                @Html.ValidationMessageFor(m => m.ConfirmPwd, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(m => m.mNickname, "暱稱", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(m => m.mNickname, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(m => m.mNickname, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="註冊" class="btn btn-default" />
            </div>
        </div>
        <br />
        @Html.ValidationSummary(null, new { @class = "text-danger" })
    </div>
}

<div>
    @Html.ActionLink("返回到登入畫面", "Login")
</div>